# .pre-commit-config.yaml
# This file defines the pre-commit hooks to be run before each commit.

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
        - id: check-added-large-files # Prevent giant files from being committed.
        - id: trailing-whitespace # Trims trailing whitespace.
          args: [ --markdown-linebreak-ext=md ]
        - id: check-ast # Checks whether the files parse as valid python.
        - id: check-case-conflict # Checks for files that would conflict in case-insensitive filesystems.
        - id: check-json # Attempts to load all JSON files to verify syntax
        - id: check-toml # Attempts to load all TOML files to verify syntax.
        - id: check-merge-conflict # Check for files that contain merge conflict strings
        - id: check-xml # Attempts to load all XML files to verify syntax
        - id: check-yaml # Attempts to load all YAML files to verify syntax
        - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
        - id: check-symlinks # Checks for symlinks which do not point to anything
        - id: no-commit-to-branch # Protect specific branches from direct checkins (`main` by default)
          stages: [ pre-commit ]
        - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source
        - id: check-added-large-files # Prevent giant files from being committed
        - id: detect-private-key # Checks for the existence of private keys.
        - id: forbid-new-submodules # Prevent addition of new git submodules.
        - id: mixed-line-ending  # Replaces mixed line ending.
          args: [--fix=auto ]
        - id: pretty-format-json  #  Checks that all your JSON files are pretty.
          args: [ --autofix ]


    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.11.2
      hooks:
        - id: ruff # Run `ruff` linter
          args: [--fix, --exit-non-zero-on-fix]
        - id: ruff-format # Run `ruff` formatter

    - repo: https://github.com/thibaudcolas/curlylint
      rev: v0.13.1
      hooks:
        - id: curlylint # Lint for invalid Django Template syntax
          types: [file]
          files: \.html$
